"""Sandboxed execution of agent-generated solver code.

Runs the code in a fresh subprocess (temp working directory)
with a wall-clock timeout and, on POSIX, CPU-time and address-space limits.
The interpreter is the same one running optimist, so OR-Tools and the standard
scientific stack installed alongside optimist are importable.

This is a resource sandbox, not a security boundary: the code is generated by
a model at the user's request and runs with the user's privileges, just as the
user's own scripts would.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path

DEFAULT_TIMEOUT_S = 120
MAX_OUTPUT_CHARS = 40_000
_MEM_LIMIT_BYTES = 6 * 1024**3


def _posix_limits(timeout_s: int):
    def set_limits() -> None:  # pragma: no cover - runs in the child process
        import resource

        resource.setrlimit(resource.RLIMIT_CPU, (timeout_s, timeout_s + 5))
        try:
            resource.setrlimit(resource.RLIMIT_AS, (_MEM_LIMIT_BYTES, _MEM_LIMIT_BYTES))
        except (ValueError, OSError):
            pass

    return set_limits


@dataclass
class RunResult:
    stdout: str
    stderr: str
    returncode: int
    duration_s: float
    timed_out: bool = False

    def as_tool_result(self) -> tuple[str, bool]:
        """Render for the model: (text, is_error)."""
        if self.timed_out:
            return (
                f"TIMED OUT after {self.duration_s:.0f}s.\n"
                f"Partial stdout:\n{self.stdout}\nPartial stderr:\n{self.stderr}",
                True,
            )
        parts = []
        if self.stdout:
            parts.append(f"stdout:\n{self.stdout}")
        if self.stderr:
            parts.append(f"stderr:\n{self.stderr}")
        if not parts:
            parts.append("(no output)")
        parts.append(f"exit code: {self.returncode} ({self.duration_s:.2f}s)")
        return "\n".join(parts), self.returncode != 0


def _truncate(text: str, limit: int = MAX_OUTPUT_CHARS) -> str:
    if len(text) <= limit:
        return text
    return text[:limit] + f"\n... [truncated, {len(text) - limit} more characters]"


def run_python(code: str, timeout_s: int = DEFAULT_TIMEOUT_S) -> RunResult:
    """Execute Python source in an isolated subprocess and capture output."""
    timeout_s = max(1, min(int(timeout_s), 600))
    with tempfile.TemporaryDirectory(prefix="optimist-run-") as workdir:
        script = Path(workdir) / "main.py"
        script.write_text(code, encoding="utf-8")
        cmd = [sys.executable, str(script)]
        preexec = _posix_limits(timeout_s) if sys.platform != "win32" else None
        start = time.monotonic()
        try:
            proc = subprocess.run(
                cmd,
                cwd=workdir,
                capture_output=True,
                text=True,
                timeout=timeout_s,
                preexec_fn=preexec,
            )
            return RunResult(
                stdout=_truncate(proc.stdout),
                stderr=_truncate(proc.stderr),
                returncode=proc.returncode,
                duration_s=time.monotonic() - start,
            )
        except subprocess.TimeoutExpired as exc:
            return RunResult(
                stdout=_truncate((exc.stdout or b"").decode("utf-8", "replace")
                                 if isinstance(exc.stdout, bytes) else (exc.stdout or "")),
                stderr=_truncate((exc.stderr or b"").decode("utf-8", "replace")
                                 if isinstance(exc.stderr, bytes) else (exc.stderr or "")),
                returncode=-1,
                duration_s=time.monotonic() - start,
                timed_out=True,
            )
