"""Sandboxed execution of agent-generated solver code.

Runs the code in a subprocess with a wall-clock timeout and, on POSIX,
CPU-time and address-space limits. The interpreter is the same one running
optimist, so OR-Tools and the standard scientific stack installed alongside
optimist are importable.

By default each run gets a throwaway temp directory. Pass ``workdir`` to run
inside a persistent session workspace instead: attachment data files live
there, and anything the code writes (intermediate CSVs, solution.json, plots)
survives for later runs in the same session.

This is a resource sandbox, not a security boundary: the code is generated by
a model at the user's request and runs with the user's privileges, just as the
user's own scripts would.
"""

from __future__ import annotations

import itertools
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path

DEFAULT_TIMEOUT_S = 120
MAX_OUTPUT_CHARS = 40_000
_MEM_LIMIT_BYTES = 6 * 1024**3

_script_counter = itertools.count(1)


def _posix_limits(timeout_s: int):
    def set_limits() -> None:  # pragma: no cover - runs in the child process
        import resource

        resource.setrlimit(resource.RLIMIT_CPU, (timeout_s, timeout_s + 5))
        try:
            resource.setrlimit(resource.RLIMIT_AS, (_MEM_LIMIT_BYTES, _MEM_LIMIT_BYTES))
        except (ValueError, OSError):
            pass

    return set_limits


@dataclass
class RunResult:
    stdout: str
    stderr: str
    returncode: int
    duration_s: float
    timed_out: bool = False

    def as_tool_result(self) -> tuple[str, bool]:
        """Render for the model: (text, is_error)."""
        if self.timed_out:
            return (
                f"TIMED OUT after {self.duration_s:.0f}s.\n"
                f"Partial stdout:\n{self.stdout}\nPartial stderr:\n{self.stderr}",
                True,
            )
        parts = []
        if self.stdout:
            parts.append(f"stdout:\n{self.stdout}")
        if self.stderr:
            parts.append(f"stderr:\n{self.stderr}")
        if not parts:
            parts.append("(no output)")
        parts.append(f"exit code: {self.returncode} ({self.duration_s:.2f}s)")
        return "\n".join(parts), self.returncode != 0


def _truncate(text: str, limit: int = MAX_OUTPUT_CHARS) -> str:
    if len(text) <= limit:
        return text
    return text[:limit] + f"\n... [truncated, {len(text) - limit} more characters]"


def _execute(code: str, cwd: Path, script: Path, timeout_s: int) -> RunResult:
    script.write_text(code, encoding="utf-8")
    cmd = [sys.executable, str(script)]
    preexec = _posix_limits(timeout_s) if sys.platform != "win32" else None
    start = time.monotonic()
    try:
        proc = subprocess.run(
            cmd,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=timeout_s,
            preexec_fn=preexec,
        )
        return RunResult(
            stdout=_truncate(proc.stdout),
            stderr=_truncate(proc.stderr),
            returncode=proc.returncode,
            duration_s=time.monotonic() - start,
        )
    except subprocess.TimeoutExpired as exc:
        def _decode(payload: bytes | str | None) -> str:
            if isinstance(payload, bytes):
                return payload.decode("utf-8", "replace")
            return payload or ""

        return RunResult(
            stdout=_truncate(_decode(exc.stdout)),
            stderr=_truncate(_decode(exc.stderr)),
            returncode=-1,
            duration_s=time.monotonic() - start,
            timed_out=True,
        )


def run_python(
    code: str, timeout_s: int = DEFAULT_TIMEOUT_S, workdir: Path | None = None
) -> RunResult:
    """Execute Python source in a subprocess and capture output.

    With ``workdir`` set, the code runs there and the directory persists
    (scripts are kept as numbered files for auditability); otherwise a temp
    directory is created and discarded.
    """
    timeout_s = max(1, min(int(timeout_s), 600))
    if workdir is not None:
        workdir.mkdir(parents=True, exist_ok=True)
        script = workdir / f"_optimist_run_{next(_script_counter):03d}.py"
        return _execute(code, cwd=workdir, script=script, timeout_s=timeout_s)
    with tempfile.TemporaryDirectory(prefix="optimist-run-") as tmp:
        tmp_path = Path(tmp)
        return _execute(code, cwd=tmp_path, script=tmp_path / "main.py", timeout_s=timeout_s)
